apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: kellnr
  name: kellnr
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: kellnr
