apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: '`R&@4NTupQxFY~nnwRnUnMd7'
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: US/Eastern
          image: lscr.io/linuxserver/mariadb:latest
          name: mariadb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: mariadb-claim0
      restartPolicy: Always
      volumes:
        - name: mariadb-claim0
          hostPath:
            path: /shared/vms/mariadb
