apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kavita
  name: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kavita
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: kavita
    spec:
      containers:
        - image: jvmilazz0/kavita:latest
          name: kavita
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /library
              name: library
            - mountPath: /kavita/config
              name: kavita-claim1
      restartPolicy: Always
      volumes:
        - name: library
          hostPath:
            path: /shared/nas/media/Library
        - name: kavita-claim1
          persistentVolumeClaim:
            claimName: kavita-claim1
