services:
  main:
    image: docker.io/ejabberd/ecs
    container_name: ejabberd
    restart: always
    env_file:
      - .env
    environment:
      - EJABBERD_MACRO_ADMIN=${XMPP_ADMIN_USER}
      - EJABBERD_MACRO_HOST=${XMPP_HOST}
      - REGISTER_ADMIN_PASSWORD=${XMPP_ADMIN_PASSWORD}
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
      - "1883:1883"
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
      - /shared/vms/xmpp/database:/home/ejabberd/database
      - /shared/vms/xmpp/logs:/home/ejabberd/logs
      - /shared/vms/xmpp/upload:/home/ejabberd/upload
      - /shared/vms/xmpp/certs:/certificates
