apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: sftpgo
  name: sftpgo
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "2022"
      port: 2022
      targetPort: 2022
  selector:
    io.kompose.service: sftpgo
