apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: sftpgo
  name: sftpgo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sftpgo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: sftpgo
    spec:
      containers:
        - image: drakkan/sftpgo:latest
          name: sftpgo
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 2022
              protocol: TCP
          volumeMounts:
            - mountPath: /shared
              name: shared
            - mountPath: /var/lib/sftpgo
              name: sftpgo-claim1
            - mountPath: /srv/sftpgo
              name: sftpgo-claim2
      restartPolicy: Always
      volumes:
        - name: shared
          hostPath:
            path: /shared
        - name: sftpgo-claim1
          persistentVolumeClaim:
            claimName: sftpgo-claim1
        - name: sftpgo-claim2
          persistentVolumeClaim:
            claimName: sftpgo-claim2
