services:
  writefreely:
    image: algernon/writefreely:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data:rw
    environment:
      - WRITEFREELY_SITE_NAME=Whispers
      - WRITEFREELY_FEDERATION=true
      - WRITEFREELY_PUBLIC_STATS=true
      - WRITEFREELY_USER_INVITES=admin
      - WRITEFREELY_ADMIN_USER=CHANGE
      - WRITEFREELY_ADMIN_PASSWORD=CHANGE