apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: forgejo
  name: forgejo
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "222"
      port: 222
      targetPort: 22
  selector:
    io.kompose.service: forgejo
