apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: forgejo
  name: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: forgejo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: forgejo
    spec:
      containers:
        - env:
            - name: FORGEJO__database__DB_TYPE
              value: postgres
            - name: FORGEJO__database__HOST
              value: 192.168.1.23:5432
            - name: FORGEJO__database__NAME
              value: forgejo
            - name: FORGEJO__database__PASSWD
              value: forgejo
            - name: FORGEJO__database__USER
              value: forgejo
            - name: USER_GID
              value: "1000"
            - name: USER_UID
              value: "1000"
          image: codeberg.org/forgejo/forgejo:8
          name: forgejo
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 22
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: forgejo-data
            - mountPath: /etc/timezone
              name: forgejo-timezone
              readOnly: true
            - mountPath: /etc/localtime
              name: forgejo-localtime
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: forgejo-data
          hostPath:
            path: /shared/nas/git
        - name: forgejo-timezone
          hostPath:
            path: /etc/timezone
        - name: forgejo-localtime
          hostPath:
            path: /etc/localtime
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
