apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: homepage-claim1
  name: homepage-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
