apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: projectsend
  name: projectsend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: projectsend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: projectsend
    spec:
      containers:
        - env:
            - name: MAX_UPLOAD
              value: "5000"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: US/Eastern
          image: lscr.io/linuxserver/projectsend:latest
          name: projectsend
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: projectsend-claim0
            - mountPath: /data
              name: projectsend-claim1
      restartPolicy: Always
      volumes:
        - name: projectsend-claim0
          hostPath:
            path: /shared/nas/vms/projectsend/config
        - name: projectsend-claim1
          hostPath:
            path: /shared/nas/vms/projectsend/shared
