services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: foundry.dax.gay
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - FOUNDRY_PASSWORD=-
      - FOUNDRY_USERNAME=-
      - FOUNDRY_ADMIN_KEY=-
    ports:
      - target: 30000
        published: 30000
        protocol: tcp