apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: foundry
  name: foundry
spec:
  type: "NodePort"
  ports:
    - name: "30000"
      port: 30000
      targetPort: 30000
  selector:
    io.kompose.service: foundry
