apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: foundry
  name: foundry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: foundry
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: foundry
    spec:
      containers:
        - env:
            - name: FOUNDRY_ADMIN_KEY
              value: '-'
            - name: FOUNDRY_PASSWORD
              value: '-'
            - name: FOUNDRY_USERNAME
              value: '-'
          image: felddy/foundryvtt:release
          name: foundry
          ports:
            - containerPort: 30000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: /shared/vms/foundry
