apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: wizarr
  name: wizarr
spec:
  type: NodePort
  ports:
    - name: "5690"
      port: 5690
      targetPort: 5690
  selector:
    io.kompose.service: wizarr
