apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: romm
  name: romm
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: romm
